### ISSUE TITLE
Past two labs were great. This lab is back to the same style.

### ISSUE THREAD

**Issue by davidjkim810** [learn-co-curriculum/redux-thunk-lab#12]
Not enough teaching or information to do this lab.

**Comment by maxwellbenton** [comment]
Hi @davidjkim810,

Thanks for this feedback. We agree and now updated this lab to be much more guided and closer to a code-along to show students how to build out a full redux-thunk application rather than leave them in the dark. This recent update should resolve this issue for students going forward.

We apologize for any frustration this lab may have caused you. Thank you for providing feedback and contributing to this lesson!
