### ISSUE TITLE
/db route does not exist

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/redux-thunk-lab#3]
@aturkewi @Lukeghenco 
The README instructs students to go to http://localhost:3000/db in their browser; however, that route does not exist. The tests work fine because there is a mock for that request, but the app does not work in the browser.

**Comment by mdo5004** [comment]
I was confused by that, too, @kwebster2. There's a linked repo "cat-api", which you need to download and run on localhost:3000, and then run redux-thunk-lab on localhost:3001 or some other number.

Running `npm start` in the cat-api folder will automatically run it on localhost:3000. Then using `npm start` in a new terminal window in the redux-thunk-lab folder, you will be asked if you want to run it on localhost:3001 because localhost:3000 is already in use.

**Comment by mdo5004** [comment]
As someone who skims when he reads, I think maybe the link to the cat-api repo needs to be more obvious or something. It's so easy to skim over details like that when reading.

**Comment by itzsaga** [comment]
Yeah, I assumed the `this repo` link was the typical lab repo.
